package com.jvmplus.vo;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_title
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.catalog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private String catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.user_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_content
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_id
     *
     * @return the value of blog.blog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_id
     *
     * @param blogId the value for blog.blog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_title
     *
     * @return the value of blog.blog_title
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_title
     *
     * @param blogTitle the value for blog.blog_title
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.catalog_id
     *
     * @return the value of blog.catalog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.catalog_id
     *
     * @param catalogId the value for blog.catalog_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.user_id
     *
     * @return the value of blog.user_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.user_id
     *
     * @param userId the value for blog.user_id
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_date
     *
     * @return the value of blog.create_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_date
     *
     * @param createDate the value for blog.create_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_date
     *
     * @return the value of blog.update_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_date
     *
     * @param updateDate the value for blog.update_date
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_content
     *
     * @return the value of blog.blog_content
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_content
     *
     * @param blogContent the value for blog.blog_content
     *
     * @mbggenerated Sun Feb 22 22:32:20 CST 2015
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
}