package com.jvmplus.vo;

import java.util.Date;

public class Catalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.catalog_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    private String catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.catalog_name
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    private String catalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.user_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.create_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.update_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.catalog_id
     *
     * @return the value of catalog.catalog_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.catalog_id
     *
     * @param catalogId the value for catalog.catalog_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.catalog_name
     *
     * @return the value of catalog.catalog_name
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.catalog_name
     *
     * @param catalogName the value for catalog.catalog_name
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.user_id
     *
     * @return the value of catalog.user_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.user_id
     *
     * @param userId the value for catalog.user_id
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.create_date
     *
     * @return the value of catalog.create_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.create_date
     *
     * @param createDate the value for catalog.create_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.update_date
     *
     * @return the value of catalog.update_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.update_date
     *
     * @param updateDate the value for catalog.update_date
     *
     * @mbggenerated Tue Feb 24 21:21:22 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}